- data-showcase/grails-app/controllers/nl/thehyve/datashowcase/TreeController.groovy
- data-showcase/grails-app/services/nl/thehyve/datashowcase/TreeService.groovy
- data-showcase/src/main/groovy/nl/thehyve/datashowcase/representation/TreeNodeRepresentation.groovy
- data-showcase/src/main/user-interface/src/app/item-table/item-table.component.ts
- data-showcase/src/main/user-interface/src/app/models/concept.ts
- data-showcase/src/main/user-interface/src/app/models/tree-node.ts
- data-showcase/src/main/user-interface/src/app/services/data.service.ts
- Improve tree fetching performance
- Temporary fix for global search.
> Tree performance

- data-showcase/src/main/user-interface/src/app/item-table/item-table.component.ts
- data-showcase/src/main/user-interface/src/app/services/data.service.ts
Fix for:
NTRDEV-153 NTRUAT-30: Checkbox on top of item table can affect either current domain or all domains ,
NTRUAT-29 Total item count can be smaller than selected item count,
NTRUAT-27 Selected items in other domains hard to keep track of
> ui improvements

- data-showcase/src/main/user-interface/src/app/app.component.css
- data-showcase/src/main/user-interface/src/app/app.component.html
- data-showcase/src/main/user-interface/src/app/app.component.spec.ts
- data-showcase/src/main/user-interface/src/app/app.module.ts
- data-showcase/src/main/user-interface/src/app/filters/checkbox-filter/checkbox-filter.component.html
- data-showcase/src/main/user-interface/src/app/info/info.component.css
- data-showcase/src/main/user-interface/src/app/info/info.component.html
- data-showcase/src/main/user-interface/src/app/info/info.component.spec.ts
- data-showcase/src/main/user-interface/src/app/info/info.component.ts
- data-showcase/src/main/user-interface/src/app/info/info.module.ts
- data-showcase/src/main/user-interface/src/app/item-table/item-table.component.html
- data-showcase/src/main/user-interface/src/app/item-table/item-table.component.ts
- data-showcase/src/main/user-interface/src/app/services/data.service.ts
- data-showcase/src/main/user-interface/src/app/shopping-cart/shopping-cart.component.css
- data-showcase/src/main/user-interface/src/app/shopping-cart/shopping-cart.component.html
- data-showcase/src/main/user-interface/src/styles.css
NTRDEV-157: Checkbox in front of search field is confusing
NTRDEV-166: Shopping cart text does not wrap correctly.
Clear items selection when filter is selected
Change description of item-table counts, add number of pages. 
NTRDEV-181: Add instructions bar
> Further UI improvements

- .travis.yml
- data-showcase/grails-app/controllers/nl/thehyve/datashowcase/ItemController.groovy
- data-showcase/grails-app/services/nl/thehyve/datashowcase/ItemService.groovy
- data-showcase/src/main/groovy/nl/thehyve/datashowcase/search/Operator.groovy
- data-showcase/src/main/groovy/nl/thehyve/datashowcase/search/SearchCriteriaBuilder.groovy
- data-showcase/src/main/user-interface/package.json
- data-showcase/src/main/user-interface/src/app/services/data.service.ts
- data-showcase/src/main/user-interface/src/app/services/resource.service.ts
- data-showcase/src/main/user-interface/src/app/services/search-parser.service.ts
- data-showcase/src/test/groovy/nl/thehyve/datashowcase/PublicItemServiceSpec.groovy
- npm import for `logic-query-parser`.
- removed unneeded explicit json parsing.
- add `contains` operator.
- make search case-insensitive.
> Backend filtering npm import

- data-showcase/grails-app/services/nl/thehyve/datashowcase/ItemService.groovy
- Fix fetching of items associated with concepts without keywords;
- Fix counts: do count distinct.
> Fix fetching of items without keywords; fix item count.

- data-showcase/grails-app/controllers/nl/thehyve/datashowcase/ItemController.groovy
- data-showcase/grails-app/services/nl/thehyve/datashowcase/ItemService.groovy
- data-showcase/src/main/user-interface/package.json
- data-showcase/src/main/user-interface/src/app/item-table/item-table.component.html
- data-showcase/src/main/user-interface/src/app/item-table/item-table.component.ts
- data-showcase/src/main/user-interface/src/app/item-table/item-table.module.ts
- data-showcase/src/main/user-interface/src/app/services/data.service.ts
Fix for [NTRDEV-209](https://jira.thehyve.nl/browse/NTRDEV-209)
> Select-all checkbox fix for pagination 

- data-showcase/grails-app/conf/application.yml
For supporting empty value strings in the import.
> Enable uploading empty strings as values.

- data-showcase/src/main/user-interface/src/app/item-table/item-table.component.html
- data-showcase/src/main/user-interface/src/app/services/data.service.ts
reset the table to the first page after new filters are selected (new item list is returned)
> Add selected page reset on filter change

- data-showcase/grails-app/controllers/nl/thehyve/datashowcase/KeywordController.groovy
- data-showcase/grails-app/controllers/nl/thehyve/datashowcase/UrlMappings.groovy
- data-showcase/grails-app/services/nl/thehyve/datashowcase/KeywordService.groovy
- data-showcase/src/main/user-interface/src/app/constants/endpoints.constants.ts
- data-showcase/src/main/user-interface/src/app/item-summary/item-summary.component.html
- data-showcase/src/main/user-interface/src/app/item-summary/item-summary.component.ts
- data-showcase/src/main/user-interface/src/app/services/data.service.ts
- data-showcase/src/main/user-interface/src/app/services/resource.service.ts
[NTRDEV-205](https://jira.thehyve.nl/browse/NTRDEV-205)
> Add keywords to summary-popup

- data-showcase/src/main/user-interface/src/app/app.component.html
- data-showcase/src/main/user-interface/src/app/app.component.spec.ts
- data-showcase/src/main/user-interface/src/app/app.component.ts
- data-showcase/src/main/user-interface/src/app/app.module.ts
- data-showcase/src/main/user-interface/src/app/filters/checkbox-filter/checkbox-filter.component.css
- data-showcase/src/main/user-interface/src/app/filters/checkbox-filter/checkbox-filter.component.html
- data-showcase/src/main/user-interface/src/app/filters/checkbox-filter/checkbox-filter.component.spec.ts
- data-showcase/src/main/user-interface/src/app/filters/filters.component.spec.ts
- data-showcase/src/main/user-interface/src/app/filters/text-filter/text-filter.component.css
- data-showcase/src/main/user-interface/src/app/filters/text-filter/text-filter.component.html
- data-showcase/src/main/user-interface/src/app/filters/text-filter/text-filter.component.spec.ts
- data-showcase/src/main/user-interface/src/app/item-summary/item-summary.component.css
- data-showcase/src/main/user-interface/src/app/item-summary/item-summary.component.html
- data-showcase/src/main/user-interface/src/app/item-summary/item-summary.component.spec.ts
- data-showcase/src/main/user-interface/src/app/item-summary/item-summary.component.ts
- data-showcase/src/main/user-interface/src/app/item-table/item-table.component.html
- data-showcase/src/main/user-interface/src/app/item-table/item-table.component.spec.ts
- data-showcase/src/main/user-interface/src/app/item-table/item-table.component.ts
- data-showcase/src/main/user-interface/src/app/logos/logos.component.spec.ts
- data-showcase/src/main/user-interface/src/app/page-ribbon/page-ribbon.component.spec.ts
- data-showcase/src/main/user-interface/src/app/services/data.service.ts
- data-showcase/src/main/user-interface/src/app/services/ds-message.service.spec.ts
- data-showcase/src/main/user-interface/src/app/services/ds-message.service.ts
- data-showcase/src/main/user-interface/src/app/services/resource.service.ts
- data-showcase/src/main/user-interface/src/app/shopping-cart/shopping-cart.component.spec.ts
- data-showcase/src/main/user-interface/src/app/tree-nodes/tree-nodes.component.css
- data-showcase/src/main/user-interface/src/app/tree-nodes/tree-nodes.component.html
- data-showcase/src/main/user-interface/src/app/tree-nodes/tree-nodes.component.spec.ts
- data-showcase/src/main/user-interface/src/styles.css
- add shopping cart update messages
- fix tests
> Add "Add to cart" button to a metadata pop-up

- data-showcase/src/main/user-interface/src/app/item-summary/item-summary.component.html
- data-showcase/src/main/user-interface/src/app/item-summary/item-summary.component.ts
> Fix item sumary fields visibility for Public environment

- data-showcase/grails-app/domain/nl/thehyve/datashowcase/Summary.groovy
> Sort summary values by frequency

- data-showcase/src/main/user-interface/src/app/item-summary/item-summary.component.html
- data-showcase/src/main/user-interface/src/app/item-summary/item-summary.component.ts
- data-showcase/src/main/user-interface/src/app/services/data.service.ts
- data-showcase/src/main/user-interface/src/app/shopping-cart/shopping-cart.component.html
- data-showcase/src/main/user-interface/src/app/shopping-cart/shopping-cart.component.ts
> Add question mark button to shopping cart view

- data-showcase/src/main/user-interface/src/app/app.component.css
- data-showcase/src/main/user-interface/src/app/filters/filters.component.css
- data-showcase/src/main/user-interface/src/app/filters/text-filter/text-filter.component.css
- data-showcase/src/main/user-interface/src/app/filters/text-filter/text-filter.component.html
- data-showcase/src/main/user-interface/src/app/item-summary/item-summary.component.html
- data-showcase/src/main/user-interface/src/app/item-summary/item-summary.component.ts
- data-showcase/src/main/user-interface/src/app/item-table/item-table.component.css
- data-showcase/src/main/user-interface/src/app/item-table/item-table.component.html
- data-showcase/src/main/user-interface/src/app/item-table/item-table.component.ts
- data-showcase/src/main/user-interface/src/app/services/data.service.ts
- data-showcase/src/main/user-interface/src/app/shopping-cart/shopping-cart.component.html
- data-showcase/src/main/user-interface/src/app/shopping-cart/shopping-cart.component.ts
- data-showcase/src/main/user-interface/src/styles.css
> Adjust column widths and paddings/margins 

- data-showcase/src/main/user-interface/src/app/app.component.css
- data-showcase/src/main/user-interface/src/app/filters/checkbox-filter/checkbox-filter.component.html
- data-showcase/src/main/user-interface/src/app/filters/filters.component.css
- data-showcase/src/main/user-interface/src/app/filters/text-filter/text-filter.component.css
- data-showcase/src/main/user-interface/src/app/filters/text-filter/text-filter.component.html
- data-showcase/src/main/user-interface/src/app/item-summary/item-summary.component.html
- data-showcase/src/main/user-interface/src/app/item-summary/item-summary.component.ts
- data-showcase/src/main/user-interface/src/app/item-table/item-table.component.css
- data-showcase/src/main/user-interface/src/app/item-table/item-table.component.html
- data-showcase/src/main/user-interface/src/app/item-table/item-table.component.ts
- data-showcase/src/main/user-interface/src/app/services/data.service.ts
- data-showcase/src/main/user-interface/src/app/shopping-cart/shopping-cart.component.html
- data-showcase/src/main/user-interface/src/app/shopping-cart/shopping-cart.component.ts
- data-showcase/src/main/user-interface/src/styles.css
>  Rename research line to research type

- data-showcase/src/main/user-interface/src/app/services/data.service.ts
- data-showcase/src/main/user-interface/src/app/tree-nodes/tree-nodes.component.html
- data-showcase/src/main/user-interface/src/app/tree-nodes/tree-nodes.component.ts
> Add tree root node, fix clear button for tree nodes filter

- data-showcase/src/main/user-interface/src/app/item-table/item-table.component.ts
- data-showcase/src/main/user-interface/src/app/shopping-cart/shopping-cart.component.html
- data-showcase/src/main/user-interface/src/app/shopping-cart/shopping-cart.component.ts
NTRDEV-262
Fixed for a shopping cart and items table
> Add a return to page 1, when sorting on any column

- data-showcase/src/main/user-interface/src/styles.css
> Change a position of the pop-up with shopping cart update message 

- data-showcase/grails-app/domain/nl/thehyve/datashowcase/Summary.groovy
- data-showcase/src/main/groovy/nl/thehyve/datashowcase/representation/SummaryRepresentation.groovy
- data-showcase/src/main/user-interface/src/app/item-summary/item-summary.component.html
> Rename 'Data stability' to status

- data-showcase/grails-app/domain/nl/thehyve/datashowcase/Summary.groovy
- data-showcase/src/main/user-interface/src/app/app.component.spec.ts
- data-showcase/src/main/user-interface/src/app/item-summary/item-summary.component.html
- data-showcase/src/main/user-interface/src/app/item-summary/item-summary.component.spec.ts
- data-showcase/src/main/user-interface/src/app/item-summary/item-summary.component.ts
- data-showcase/src/main/user-interface/src/app/item-summary/item-summary.module.ts
>  Add item values filter pipe to replace back-end sorting of values 

- data-showcase/src/main/user-interface/src/app/filters/checkbox-filter/checkbox-filter.component.html
> Change checkbox filter description (plural) to singular.

- data-showcase/grails-app/services/nl/thehyve/datashowcase/ItemService.groovy
- data-showcase/src/main/user-interface/src/app/item-table/item-table.component.html
> Replace labelLong with short label, fix the sorting in the itemTable

- data-showcase/grails-app/services/nl/thehyve/datashowcase/ItemService.groovy
> Fix hibernate items query, when sorting on p.lineOfResearch

- data-showcase/src/main/user-interface/src/app/app.component.css
- data-showcase/src/main/user-interface/src/app/filters/text-filter/info/info.component.html
- data-showcase/src/main/user-interface/src/app/shopping-cart/shopping-cart.component.html
- data-showcase/src/main/user-interface/src/app/shopping-cart/shopping-cart.component.ts
- data-showcase/src/main/user-interface/src/styles.css
[TMT-540](https://jira.thehyve.nl/browse/TMT-540)
> Improve responsiveness of the UI
